[pytest]
DJANGO_SETTINGS_MODULE = test_settings
python_files = tests.py test_*.py *_tests.py
testpaths = tests
pythonpath = .
addopts =
    --verbose
    --strict-markers
    --tb=short
markers =
    accessibility: marks tests that check accessibility using axe-core via selenium
    selenium: marks tests that use a selenium webdriver
